# Generated by Django 4.2.2 on 2023-06-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistuser',
            name='tg_connect',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todolistuser',
            name='telegram_id',
            field=models.CharField(default='None', max_length=150, verbose_name='Телеграм пользователя'),
        ),
    ]
