# Generated by Django 4.2.2 on 2023-06-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_todolistuser_tg_connect_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolistuser',
            name='tg_connect',
        ),
    ]
